---
#
# Playbook for deploying Tripleo OpenStack for OpenShift in ScaleLab
#

# Do not gather facts for rebuilding undercloud
- name: Rebuild Undercloud
  hosts: undercloud
  gather_facts: false
  remote_user: root
  vars_files:
    - vars/data.yml
    - vars/deploy.yml
  roles:
    - validate_vars
    - rebuild-undercloud

- name: Run initial setup tasks
  hosts: undercloud
  gather_facts: true
  remote_user: root
  vars_files:
    - vars/data.yml
    - vars/deploy.yml
  pre_tasks:
    - name: Get timestamp
      command: date -u +%Y%m%d-%H%M%S
      delegate_to: localhost
      register: current_ts

    - name: Set remote log directory
      set_fact:
        log_dir: /home/stack/alderaan-deploy/log/{{current_ts.stdout}}

    - name: Set local Artifact Directory
      set_fact:
        artifact_dir: artifacts/{{version}}-alderaan-{{current_ts.stdout}}

    - name: Ensure artifact directory exists
      file:
        path: "{{artifact_dir}}"
        state: directory
      delegate_to: localhost
  roles:
    - undercloud-prepare-host

- name: Run OSP install
  hosts: undercloud
  gather_facts: false
  remote_user: stack
  vars_files:
    - vars/data.yml
    - vars/deploy.yml
  roles:
    - undercloud-install
    - undercloud-introspection
    - overcloud-prepare-templates
    - overcloud-deploy
    - post-deploy
