---
# tasks file for overcloud-deploy

- name: OSP11 Install ostag
  pip:
    state: latest
    virtualenv: /home/stack/alderaan-deploy/ostag-venv
    name: "{{item}}"
  with_items:
    - pip
    - git+https://github.com/redhat-performance/ostag#egg=ostag
  when: version == '11'

- name: OSP11 Fix os-client-config version for ostag
  pip:
    name: os-client-config
    version: 1.29.0
    virtualenv: /home/stack/alderaan-deploy/ostag-venv
  when: version == '11'

- name: OSP13 Copy pin python script to Undercloud
  copy:
    src: pin.py
    dest: /home/stack/alderaan-deploy/pin.py
    mode: 0744
  when: version == '13'

- name: Template the Pinning script
  template:
    src: pin-nodes.sh.j2
    dest: /home/stack/alderaan-deploy/pin-nodes.sh
    mode: 0744

- name: Pin Nodes Block
  block:
    - name: Pin the nodes
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        { time /home/stack/alderaan-deploy/pin-nodes.sh 2>&1 | tee -a {{log_dir}}/pin-nodes.log ; } 2>> {{log_dir}}/pin-nodes.log
  always:
    - name: Collect Pin Nodes Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/alderaan-deploy_log"
        mode: pull

- name: Template deploy script
  template:
    src: overcloud-deploy.sh.j2
    dest: /home/stack/alderaan-deploy/overcloud-deploy.sh
    mode: 0744

- name: Check if "alderaan-undercloud" tmux exists
  become: true
  shell: tmux ls | grep -q alderaan-undercloud
  register: tmux_install_exists
  failed_when: tmux_install_exists.rc >= 2

- name: Setup "alderaan-undercloud" tmux
  become: true
  shell: |
    tmux -2 new-session -d -s alderaan-undercloud -n 'root'
    tmux send-keys "cd /var/log" C-m
    tmux new-window -t alderaan-undercloud:2 -n 'alderaan-deploy-log'
    tmux send-keys "su - stack" C-m
    tmux send-keys ". stackrc" C-m
    tmux send-keys "cd /home/stack/alderaan-deploy/log" C-m
    tmux new-window -t alderaan-undercloud:3 -n 'alderaan-undercloud'
    tmux send-keys "su - stack" C-m
    tmux send-keys ". stackrc" C-m
    tmux select-window -t alderaan-undercloud:2
  when: tmux_install_exists.rc == 1

- name: Overcloud Deploy Block
  block:
    - name: Deploy the Overcloud
      shell: |
        . /home/stack/stackrc
        /home/stack/alderaan-deploy/overcloud-deploy.sh {{log_dir}}
  rescue:
     # Collect additional items to sweep into alderaan-deploy/log for debugging in event of failure
    - name: Collect OpenStack Ironic/Heat/Mistral/Nova log files
      become: true
      shell: |
        mkdir -p {{log_dir}}/ironic
        cp -r /var/log/ironic/* {{log_dir}}/ironic
        mkdir -p {{log_dir}}/heat
        cp -r /var/log/heat/* {{log_dir}}/heat
        mkdir -p {{log_dir}}/mistral
        cp -r /var/log/mistral/* {{log_dir}}/mistral
        mkdir -p {{log_dir}}/nova
        cp -r /var/log/nova/* {{log_dir}}/nova
        mkdir -p {{log_dir}}/templates
        cp -r /home/stack/templates/* {{log_dir}}/templates

    - name: Dump OpenStack Data
      shell: |
        set -o pipefail
        . /home/stack/stackrc
        openstack baremetal node list 2>&1 | tee -a {{log_dir}}/overcloud-deploy_openstack-baremetal-node-list.log
        openstack baremetal node list | grep None | awk '{print $2}' | xargs -I % openstack baremetal node show % 2>&1 | tee -a {{log_dir}}/overcloud-deploy_openstack-baremetal-node-show.log
        openstack server list --all 2>&1 | tee -a {{log_dir}}/overcloud-deploy_openstack-server-node-list.log
        openstack stack resource list overcloud 2>&1 | tee -a {{log_dir}}/overcloud-deploy_openstack-stack-resource-list.log
        openstack stack failures list overcloud 2>&1 | tee -a {{log_dir}}/overcloud-deploy_openstack-stack-failures-list.log

    - name: Ensure playbook stops under this condition
      fail:
        msg: Overcloud deploy failures.
  always:
    - name: Collect Overcloud Deploy Artifacts
      synchronize:
        src: "{{log_dir}}"
        dest: "{{artifact_dir}}/alderaan-deploy_log"
        mode: pull
