---
# tasks file for overcloud-prepare-templates

- name: Copy THT Files into stack user templates directory
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: stack
    group: stack
    mode: "{{item.mode | default('0644')}}"
  with_items: "{{overcloud_tht_files}}"

- name: Render templatized THT into stack user templates directory
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: stack
    group: stack
  with_items: "{{overcloud_tht_templates}}"

- name: Place version metadata json file in /etc
  become: true
  template:
    src: templates/version.json.j2
    dest: /etc/version.json
    owner: stack
    group: stack

- name: Render the network setup script
  template:
    src: templates/create_public_cluster_network.sh.j2
    dest: /home/stack/alderaan-deploy/create_public_cluster_network.sh
    mode: 0755
    owner: stack
    group: stack
