---
# tasks file for overcloud-prepare-templates

- name: Clone the templates repo
  local_action:
    module: git
    repo: "{{ templates_repo }}"
    dest: "{{ playbook_dir }}/templates/"

- name: Copy over folder for this deployment
  copy:
    src: "{{ playbook_dir }}/templates/{{ templates_repo_path|default('scale-ci/', true) }}"
    dest: "/home/stack/templates"
    owner: stack
    group: stack

- name: Replace controller type with our controller type
  lineinfile:
    dest: "/home/stack/templates/network-environment.yaml"
    regexp: "^  OS::TripleO::Controller::Net::SoftwareConfig"
    state: absent

- name: Replace controller type with our controller type
  lineinfile:
    dest: "/home/stack/templates/network-environment.yaml"
    line: "  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/templates/nic-configs/{{controller_type}}-controller.yaml"
    insertafter: "^resource_registry:"
    state: present

- name: Template deploy.yml
  template:
    src: deploy.yaml.j2
    dest: /home/stack/templates/deploy.yaml

- name: Place version metadata json file in /etc
  become: true
  template:
    src: templates/version.json.j2
    dest: /etc/version.json
    owner: stack
    group: stack
